name             'hockeypuck'
maintainer       'Michael Avila'
maintainer_email 'me@michaelavila.com'
license          ''
description      'Installs/Configures hockeypuck'
long_description 'Installs/Configures hockeypuck'
version          '0.1.1'
